#!/bin/zsh

alias brew='arch -x86_64 brew'

# DOCKER COMMANDS
alias dcu='docker-compose up'
alias dcr='docker-compose restart'
alias dcd='docker-compose down'
alias dce='docker-compose exec'

# GIT COMMANDS
alias gs='git status'
alias gco='git commit'
alias gb='git branch'
alias gch='git checkout'
alias gl='git log -n 10 --oneline'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gap='git add --patch'
alias gpf='git push --force-with-lease'
alias grm='git checkout master && git pull && git checkout - && git rebase master'
alias gra='git rebase -i --autosquash'
alias grc='git rebase --continue'
alias gre='git rebase --edit-todo'
alias grs='git restore --staged'

# DEVELOPMENT COMMANDS
alias wo='workon'
